== Building and running Cyberismo locally from source

=== Prerequisites

See {{#xref}}"cardKey":"docs_17"{{/xref}} for information about common prerequisites for all installation methods.

Install Node.js. The currently supported Node.js version is the latest LTS, v20.10.0 or later. Node.js is downloadable from https://nodejs.org/.

When building Cyberismo on Windows, the build process automatically installs the required dependencies (Clingo and libraries) using a prebuilt package by Cyberismo.

=== Building

Take the following steps:

. Clone the source repository:

  $ git clone https://github.com/CyberismoCom/cyberismo.git

. Change to the source directory. If you previously cloned the repository, pull the latest changes:

  $ cd cyberismo
  $ git pull origin main # Optional

. Install pnpm with npm command:

  $ npm install -g pnpm

. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g


=== Running

After building and installing, run `cyberismo --help` to see the command-line help.
