== Building and running Cyberismo locally from source

=== Prerequisites

See {{#xref}}"cardKey":"docs_17"{{/xref}} for information about common prerequisites for all installation methods.

Install the following:

* Node.js v22 LTS or later, downloadable from https://nodejs.org/.
* Visual Studio Build Tools 2022 with the "Desktop development with C++" workload (provides MSVC and Windows SDK).
* CMake 3.x, downloadable from https://cmake.org/.
* Python 3, downloadable from https://www.python.org/.

These tools are used to build the bundled Clingo answer set programming runtime from source as part of `pnpm install`.

=== Building

Take the following steps:

. Clone the source repository, including the Clingo submodule:

  $ git clone --recurse-submodules https://github.com/CyberismoCom/cyberismo.git

+
If you previously cloned the repository, change to the source directory and pull the latest changes:

  $ cd cyberismo
  $ git pull origin main
  $ git submodule update --init --recursive

. Install pnpm with the npm command:

  $ npm install -g pnpm

. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g

`pnpm install` builds the bundled Clingo runtime as part of installing the `@cyberismo/node-clingo` workspace package.

=== Running

After building and installing, run `cyberismo --help` to see the command-line help.
