= Cyberismo: a tool for making a difference in cybersecurity

Visit link:https://cyberismo.com/solution[Cyberismo solution] for an overview and link:https://docs.cyberismo.com[Cyberismo documentation] for instructions and tutorials.

== Copyright

Copyright © Cyberismo Ltd and contributors 2024

== License and trademark policy

This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License version 3 as published by the Free Software Foundation.

The use of Cyberismo trademark is governed by the Cyberismo open source trademark policy. See separate file TRADEMARK.adoc.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

See separate file LICENSE for more information.

Notice that while Cyberismo Ltd enforces the license of this software, the license does not affect the content produced by Cyberismo tool users. Users can be confident that the resulting documents and resources produced with Cyberismo tools and software are not affected by the licenses that Cyberismo Ltd uses to distribute the software.

== Contributing

See separate file CONTRIBUTING.

== Development

=== Environment
Copy *env.example* files to respective *.env* files

=== Instal Dependencies
[source, shell]
----
    pnpm install
----

=== Run Project
[source, shell]
----
    pnpm dev
----
Backend is accessible at http://localhost:3000

Frontend is accessible at http://localhost:5173

