import { defineConfig } from 'vite-plus';

export default defineConfig({
  lint: {
    plugins: ['oxc', 'typescript', 'unicorn', 'react', 'promise'],
    categories: {
      correctness: 'warn',
    },
    env: {
      builtin: true,
      es2024: true,
      // `no-undef` is already off for .ts/.tsx (TypeScript catches those), so
      // this only governs the .mjs/.js build and release scripts.
      node: true,
      browser: true,
    },
    ignorePatterns: [
      '**/dist/*',
      '**/init.js',
      '**/coverage/*',
      '**/node_modules/*',
      'eslint.config.js',
      'eslint.config.mjs',
    ],
    rules: {
      'constructor-super': 'error',
      'for-direction': 'error',
      'getter-return': 'error',
      'no-async-promise-executor': 'error',
      'no-case-declarations': 'error',
      'no-class-assign': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-const-assign': 'error',
      'no-constant-binary-expression': 'error',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-delete-var': 'error',
      'no-dupe-class-members': 'error',
      'no-dupe-else-if': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-empty-pattern': 'error',
      'no-empty-static-block': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-fallthrough': 'error',
      'no-func-assign': 'error',
      'no-global-assign': 'error',
      'no-import-assign': 'error',
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-loss-of-precision': 'error',
      'no-misleading-character-class': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-nonoctal-decimal-escape': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-redeclare': 'error',
      'no-regex-spaces': 'error',
      'no-self-assign': 'error',
      'no-setter-return': 'error',
      'no-shadow-restricted-names': 'error',
      'no-sparse-arrays': 'error',
      'no-this-before-super': 'error',
      'no-unassigned-vars': 'error',
      'no-undef': 'error',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'no-unsafe-optional-chaining': 'error',
      'no-unused-labels': 'error',
      'no-unused-private-class-members': 'error',
      'no-unused-vars': 'error',
      'no-useless-assignment': 'error',
      'no-useless-backreference': 'error',
      'no-useless-catch': 'error',
      'no-useless-escape': 'error',
      'no-with': 'error',
      'preserve-caught-error': 'error',
      'require-yield': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',
      'no-array-constructor': 'error',
      'no-unused-expressions': 'error',
      'typescript/ban-ts-comment': 'error',
      'typescript/no-duplicate-enum-values': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extra-non-null-assertion': 'error',
      'typescript/no-misused-new': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-optional-chain': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-this-alias': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unsafe-declaration-merging': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-namespace-keyword': 'error',
      'typescript/triple-slash-reference': 'error',
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
    overrides: [
      {
        files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
        rules: {
          'constructor-super': 'off',
          'getter-return': 'off',
          'no-class-assign': 'off',
          'no-const-assign': 'off',
          'no-dupe-class-members': 'off',
          'no-dupe-keys': 'off',
          'no-func-assign': 'off',
          'no-import-assign': 'off',
          'no-new-native-nonconstructor': 'off',
          'no-obj-calls': 'off',
          'no-redeclare': 'off',
          'no-setter-return': 'off',
          'no-this-before-super': 'off',
          'no-undef': 'off',
          'no-unreachable': 'off',
          'no-unsafe-negation': 'off',
          'no-var': 'error',
          'no-with': 'off',
          'prefer-const': 'error',
          'prefer-rest-params': 'error',
          'prefer-spread': 'error',
        },
      },
      {
        files: ['**/*.ts', '**/*.tsx'],
        rules: {
          'typescript/consistent-type-imports': 'error',
        },
      },
      {
        // Parity with the former `nodeConfig` in eslint.config.js: the
        // type-aware promise rules only ever applied to the Node packages.
        files: [
          'tools/backend/**/*.ts',
          'tools/cli/**/*.ts',
          'tools/data-handler/**/*.ts',
          'tools/mcp/**/*.ts',
          'tools/migrations/**/*.ts',
          'tools/node-clingo/**/*.ts',
        ],
        rules: {
          'typescript/no-floating-promises': 'error',
          'typescript/no-misused-promises': 'error',
          'promise/catch-or-return': 'error',
          'promise/no-promise-in-callback': 'error',
          'promise/always-return': 'off',
        },
      },
      {
        files: ['tools/app/**/*.ts', 'tools/app/**/*.tsx'],
        rules: {
          'react/rules-of-hooks': 'error',
          'react/exhaustive-deps': 'warn',
          'react/only-export-components': [
            'warn',
            { allowConstantExport: true },
          ],
        },
      },
      {
        files: [
          'tools/app/e2e/**/*.ts',
          'tools/app/scripts/**/*.js',
          'tools/app/playwright.config.ts',
        ],
        rules: {
          'react/rules-of-hooks': 'off',
          'react/exhaustive-deps': 'off',
          'react/only-export-components': 'off',
          'no-empty-pattern': 'off',
        },
      },
    ],
    options: {
      typeAware: true,
      // Left off for parity with the previous pipeline: `tsc -p
      // tsconfig.build.json` only ever covered `src/**`, so turning this on
      // type-checks the test dirs for the first time and surfaces ~60
      // pre-existing errors. Worth doing, but as its own piece of work.
      typeCheck: false,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
  },
  fmt: {
    singleQuote: true,
    printWidth: 80,
    sortPackageJson: false,
    ignorePatterns: [
      '.next/',
      '.turbo/',
      '.tmp/',
      '_next/',
      '__tmp__/',
      'dist/',
      'node_modules/',
      'target/',
      'compiled/',
      'examples/',
      '**/test-data/',
      '.github/',
      '*.hbs',
      'tools/assets/src/static/ui-bundle',
      'pnpm-lock.yaml',
      'module-test/',
      'tools/node-clingo/external',
      'tools/app/e2e/assets/e2e-keys.json',
      'docs',
      'tools/app/test-results/',
      'tools/app/playwright-report/',
      'tools/app/playwright/.cache/',
    ],
  },
});
