:sectnums:
This tutorial shows how to create a new Cyberismo project with the base module and open it in the app.

If you would rather look at a finished project than build an empty one, start with {{#xref}}"cardKey":"docs_12"{{/xref}} instead. It needs nothing installed and shows what a real secure development project looks like.

== Install Cyberismo

Cyberismo requires https://nodejs.org/[Node.js] v22 LTS or later. The Clingo reasoning engine ships as a prebuilt binary, so there is nothing else to install.

[source,console]
----
$ npm install -g @cyberismo/cli
----

For other installation methods, including Docker, Podman and building from source, see {{#xref}}"cardKey":"docs_13"{{/xref}}.

== Create a project

First, check the command-line help for creating a project by executing the following command:

[source,console]
----
$ cyberismo create project --help
Usage: cyberismo create project [options] <name> <prefix> <path>

Create a project

Arguments:
  name        Name for project.
              Name can contain letters (a-z|A-Z), spaces, underscores or hyphens.
  prefix      Prefix that will be part of each card's card key. Prefix can be 3-10 characters (A-Z)
  path        Path where project is created.
              Note that folder is automatically created.

Options:
  -h, --help  display help for command
----

Create a new project called "Cyberismo tutorial" that has the card key prefix tutorial in the directory `cyberismo-tutorial` with the following command:

[source,console]
----
$ cyberismo create project "Cyberismo tutorial" tutorial cyberismo-tutorial
----

When Cyberismo creates a new project, it asks which of the default modules you want to import. Press Space to select 'Base module', then press Enter:

[source,console]
----
$ cyberismo create project "Cyberismo tutorial" tutorial cyberismo-tutorial
? Select modules to import (Press <space> to select, <a> to toggle all, <i> to invert selection, and <enter> to proceed)
❯◉ Base module
 ◯ Cyberismo EU Cyber Resilience Act
 ◯ ISMS Essentials
 ◯ Secure development essentials
----

After pressing Enter, wait for the import to complete.

TIP: To start from a ready-made process rather than an empty project, select one of the other modules here as well. See {{#xref}}"cardKey":"docs_b9w4zfng"{{/xref}} for what each one gives you.

=== Import the base module later

If you did not import the 'base' module while creating the project, you can still do it with the following command:

[source,console]
----
$ cyberismo import module base -p cyberismo-tutorial
----

== Create a page

The base module includes a page template. To create the first card in the new project, execute the following command:

[source,console]
----
$ cd cyberismo-tutorial
$ cyberismo create card base/templates/page
----

== Start the Cyberismo app

You can view and edit the new project and its first card with the Cyberismo app. To start the app, execute the following command:

[source,console]
----
$ cyberismo app
----

Then open a browser and navigate to http://localhost:3000/.

You now have a working project: a card you can edit, a workflow you can move it through, and a logic program already computing its state.

:!sectnums:

== Next

* {{#xref}}"cardKey":"docs_iv4h2usw"{{/xref}} and {{#xref}}"cardKey":"docs_x9fat7ty"{{/xref}} cover the everyday actions.
* {{#xref}}"cardKey":"docs_xpzkgk9n"{{/xref}} defines the vocabulary: card, card type, workflow, link, template, module.
* {{#xref}}"cardKey":"docs_b9w4zfng"{{/xref}} is where you pick up a ready-made process.
