== Building and running Cyberismo locally from source

=== Prerequisites

See {{#xref}}"cardKey":"docs_17"{{/xref}} for information about common prerequisites for all installation methods.

Install the following:

* Node.js v22 LTS or later, downloadable from https://nodejs.org/.
* The Xcode Command Line Tools, which provide a C++20 toolchain and GNU Make:

  $ xcode-select --install

* CMake 3.x or newer and Python 3. With https://brew.sh[Homebrew]:

  $ brew install cmake python

These tools are used to build the bundled Clingo answer set programming runtime from source as part of `pnpm install`.

=== Building

Take the following steps:

. Clone the source repository, including the Clingo submodule:

  $ git clone --recurse-submodules https://github.com/CyberismoCom/cyberismo.git
  $ cd cyberismo

+
If you previously cloned the repository, change to the source directory and pull the latest changes:

  $ cd cyberismo
  $ git pull origin main
  $ git submodule update --init --recursive

. Enable pnpm. Cyberismo pins the pnpm version it is built with, and corepack, which ships with Node.js, picks that version automatically:

  $ corepack enable

+
Corepack installs the `pnpm` command next to the Node.js binary. If Node.js is installed system-wide rather than through Homebrew or a version manager, the command fails with a permission error, and you need to run it as root:

  $ sudo corepack enable

+
If your Node.js installation does not include corepack, run `npm install -g pnpm` instead, with the same privileges.

. Set up the directory that pnpm installs global commands into:

  $ pnpm setup

+
This adds the directory to `PATH` in your shell startup file, which only affects shells started afterwards, so open a new terminal before continuing.

. In the new terminal, build Cyberismo and install the `cyberismo` command:

  $ cd cyberismo
  $ pnpm install
  $ pnpm build
  $ pnpm add -g .

+
`pnpm install` builds the bundled Clingo runtime as part of installing the `@cyberismo/node-clingo` workspace package.

=== Running

After building and installing, run `cyberismo --help` to see the command-line help.
