== Building and running Cyberismo locally from source

=== Prerequisites

See {{#xref}}"cardKey":"docs_17"{{/xref}} for information about common prerequisites for all installation methods.

Install the following:

* Node.js v22 LTS or later, downloadable from https://nodejs.org/.
* The Xcode Command Line Tools, which provide a C++20 toolchain and GNU Make:

  $ xcode-select --install

* CMake 3.x and Python 3. With https://brew.sh[Homebrew]:

  $ brew install cmake python

These tools are used to build the bundled Clingo answer set programming runtime from source as part of `pnpm install`.

=== Building

Take the following steps:

. Clone the source repository, including the Clingo submodule:

  $ git clone --recurse-submodules https://github.com/CyberismoCom/cyberismo.git

+
If you previously cloned the repository, change to the source directory and pull the latest changes:

  $ cd cyberismo
  $ git pull origin main
  $ git submodule update --init --recursive

. Install pnpm with the npm command:

  $ npm install -g pnpm

. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g

`pnpm install` builds the bundled Clingo runtime as part of installing the `@cyberismo/node-clingo` workspace package.

=== Running

After building and installing, run `cyberismo --help` to see the command-line help.
