== Building and running Cyberismo locally from source

=== Prerequisites

See {{#xref}}"cardKey":"docs_17"{{/xref}} for information about common prerequisites for all installation methods.

Install the following:

* Node.js v22 LTS or later, downloadable from https://nodejs.org/.
* A C++20 toolchain (GCC 14+ or recent Clang), CMake 3.x, GNU Make, and Python 3. These are used to build the bundled Clingo answer set programming runtime from source.

Install the build tools using your distribution's package manager:

  $ sudo apt-get install -y g++ make cmake python3  # Ubuntu/Debian
  $ sudo dnf install -y gcc-c++ make cmake python3  # Fedora/RHEL
  $ sudo pacman -S --needed gcc make cmake python   # Arch Linux
  $ sudo apk add g++ make cmake python3             # Alpine

=== Building

Take the following steps:

. Clone the source repository, including the Clingo submodule:

  $ git clone --recurse-submodules https://github.com/CyberismoCom/cyberismo.git

+
If you previously cloned the repository, change to the source directory and pull the latest changes:

  $ cd cyberismo
  $ git pull origin main
  $ git submodule update --init --recursive

. Install pnpm with the npm command:

  $ npm install -g pnpm

. Execute the following commands:

  $ pnpm setup
  $ pnpm install
  $ pnpm build
  $ pnpm link -g

`pnpm install` builds the bundled Clingo runtime as part of installing the `@cyberismo/node-clingo` workspace package.

=== Running

After building and installing, run `cyberismo --help` to see the command-line help.
