== Introduction

The configuration of a graph consists of a graph model and a graph view, allowing several different graph views to be created based on a single graph model.

See xref:docs_hbskjelr.adoc[Implementing graphs] for a longer introduction to graphs.

== Managing graph models using the configuration editor

Use the configuration editor to manage graph models.

=== Creating a graph model

To create a new graph model:

1. Open the **configuration editor** in the Cyberismo app by setting the path part of the URL to `/configuration`.
2. Select **Graph Models** from the tree menu on the left, or use the **New Resource** menu in the toolbar.
3. Click **Create new** on the Graph Models overview page.
4. Enter an identifier for the new graph model and confirm.

The new graph model will be created with default files and the editor will open.

When choosing a name for your graph model, see xref:docs_8.adoc[Naming conventions].

=== Editing graph model metadata

In the graph model editor, you can edit the following properties:

* **Identifier**: The technical name of the graph model. Renaming is supported.
* **Display name**: The name shown in user interfaces (e.g., "Workflow").
* **Description**: A description of the graph model (e.g., "A model for a diagram of the state machine of a workflow").
* **Category**: The category of the graph model (e.g., "General").

Each field has individual save and cancel buttons that appear when you make changes.

=== Editing the graph model implementation

The graph model implementation file (`model.lp`) can be edited using the built-in text editor in the configuration editor. In the tree menu, expand the graph model to see its files and click on the model file to open it.

=== Deleting a graph model

To delete a graph model, open it in the editor and use the context menu (three-dot button) in the toolbar to select **Delete Resource**.

== Managing graph models using the command-line tool

You can also manage graph models using the Cyberismo command-line tool.

To see a list of the available graph models, use the following command:

  $ cyberismo show graphModels

To see the help for how to create a graph model, use the following command:

  $ cyberismo create graphModel --help

To create a new graph model, for example `myGraphModel`, use the following command:

  $ cyberismo create graphModel myGraphModel

Cyberismo will create the following files:

* Graph model metadata file `.cards/local/graphModels/myGraphModel.json`
* Directory `.cards/local/graphModels/myGraphModel/`
* Model file `.cards/local/graphModels/myGraphModel/model.lp`

If the card prefix of your Cyberismo project is `example`, then the full name of the new graph model will be `example/graphModels/myGraphModel`.

== Graph model JSON file format

Basic metadata for a graph model is defined in a JSON file that follows the https://github.com/CyberismoCom/cyberismo/blob/main/tools/assets/src/schema/resources/graphModelSchema.json[graph model schema], as described in the following table.

NOTE: Do not edit the JSON files directly. The configuration editor provides a graphical interface for managing graph model metadata and a built-in text editor for the model implementation file.

.The properties of a graph model JSON file
|===
|Property|Type|Description|Required

|**name**
|`string`
|The technical name of the graph model
| &#10003; Yes

|**displayName**
|`string`
|The name of the graph model as it should be displayed in the user interface. For example, 'Workflow'.
| &#10003; Yes

|**description**
|`string`
|A description of the graph model. For example, "A model for a diagram of the state machine of a workflow".
| No

|**category**
|`string`
| The category of the graph model. For example, 'General'.
| &#10003; Yes

|===

Additional properties are not allowed.

== Graph model implementation

The graph model implementation is a logic program that uses the Clingraph conventions to describe a graph. When the graph model is executed, it is combined with a graph view and the main Cyberismo logic program, so you can write rules that convert your data into nodes and edges of a graph.

The implementation of graphs is discussed in detail in xref:docs_hbskjelr.adoc[Implementing graphs].

== Mapping to a logic program

Cyberismo does not currently generate logic program facts for graph models.