# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & test (macOS)

on:
  push:
    branches:
      - main
      - temp-main
  pull_request:
    branches: [ "main", "temp-main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Install homebrew
      if: runner.os == 'macOS'
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install clingo
      if: runner.os == 'macOS'
      run: |
        brew install clingo --ignore-dependencies

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cyberismo'
    - name: Checkout module-base repository for testing purposes
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/module-base
        path: .tmp/module-base
        ref: main
    - name: Checkout cyberismo-docs repository for testing purposes
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/cyberismo-docs
        path: .tmp/cyberismo-docs
        ref: main
    - run: pnpm install
    - run: pnpm --filter=app exec cypress install
    - run: pnpm prettier-check
    - run: pnpm build
    - run: pnpm link --global
    - run: pnpm test
