# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & test (Ubuntu)

on:
  push:
    branches:
      - main
      - temp-main
  pull_request:
    branches: [ "main", "temp-main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Install Clingo
      run: sudo apt-get update && sudo apt-get install -y gringo
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cyberismocom'
    - name: Checkout module-base repository for testing purposes
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/module-base
        path: module-base
        ref: main
    - run: npm ci
    - run: npm run prettier-check
    - run: npm run build
    - run: npm test
