# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & test (Windows)

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.x]

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cyberismocom'
    - run: npm ci
    - run: npm run build
    - run: npm test
