# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & test (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main", "temp-main" ]

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        node-version: ["${{ vars.NODE_VERSION }}"]

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Check for changes in node-clingo
      uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3
      id: changes
      with:
        filters: |
          node_clingo:
            - 'tools/node-clingo/**'
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@505e6394dae86d6a5c7fbb6e3fb8938e3e863830 # v3
      if: steps.changes.outputs.node_clingo == 'true'
      with:
        python-version: 3.12
        auto-update-conda: true
        activate-environment: cyberismo
        environment-file: environment.yml
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cyberismo'
    - name: Set up Ruby
      uses: ruby/setup-ruby@829114fc20da43a41d27359103ec7a63020954d4 # v1
      with:
        ruby-version: '3.2'
    - name: Install asciidoctor-pdf
      run: |
        gem install --no-document asciidoctor-pdf rouge
    - name: Checkout cyberismo-docs repository for testing purposes
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/cyberismo-docs
        path: .tmp/cyberismo-docs
        ref: main
        set-safe-directory: false
    - run: pnpm install
    - run: pnpm --filter=app exec cypress install
    - run: pnpm build
    - run: pnpm link --global
    - run: pnpm test
      env:
        CYBERISMO_GIT_USER: ${{ secrets.CYBERISMO_GIT_USER }}
        CYBERISMO_GIT_TOKEN: ${{ secrets.CYBERISMO_GIT_TOKEN }}
