# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build & test (Ubuntu)

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ "main", "temp-main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: read
      packages: write

    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Install clingo
      run: |
        sudo apt-get update
        sudo apt-get install -y gringo
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@cyberismo'
    - name: Set up Ruby
      uses: ruby/setup-ruby@829114fc20da43a41d27359103ec7a63020954d4 # v1
      with:
        ruby-version: '3.2'
    - name: Install asciidoctor-pdf
      run: |
        gem install --no-document asciidoctor-pdf rouge
    - name: Checkout module-base repository for testing purposes
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/module-base
        path: .tmp/module-base
        ref: main
    - name: Checkout cyberismo-docs repository for testing purposes
      uses: actions/checkout@v4
      with:
        repository: CyberismoCom/cyberismo-docs
        path: .tmp/cyberismo-docs
        ref: main
    - run: pnpm install
    - run: pnpm --filter=app exec cypress install
    - run: pnpm prettier-check
    - run: pnpm build
    - run: pnpm link --global
    - run: pnpm test
      env:
        CYBERISMO_GIT_USER: ${{ secrets.CYBERISMO_GIT_USER }}
        CYBERISMO_GIT_TOKEN: ${{ secrets.CYBERISMO_GIT_TOKEN }}
