name: Test Image

on:
  pull_request:
    branches:
      - main
      - temp-main



jobs:
  test-image:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        node-version: [${{ vars.NODE_VERSION }}]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3
        with:
          install: true

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          context: .
          file: Dockerfile
          tags: |
            cyberismo:latest
          load: true

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cyberismocom'

      - name: Checkout cyberismo-docs repository for testing purposes
        uses: actions/checkout@v4
        with:
          repository: CyberismoCom/cyberismo-docs
          path: .tmp/cyberismo-docs
          ref: main
      - run: pnpm install --ignore-scripts
      - name: Check that cyberismo is not already installed
        run: |
          if command -v cyberismo &> /dev/null; then
            echo "cyberismo is already installed"
            exit 1
          fi

      - name: Setup cyberismo script
        run: |
          chmod +x scripts/cyberismo
          echo "$(pwd)/scripts" >> $GITHUB_PATH

      - name: Run CLI tests
        run: |
          cd tools/cli
          pnpm test


