name: Test Image

on:
  pull_request:
    branches:
      - main



jobs:
  test-image:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        node-version: [22.x]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Build and push multi-arch Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          tags: |
            cyberismo:latest
          load: true

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@cyberismocom'
      - name: Checkout module-base repository for testing purposes
        uses: actions/checkout@v4
        with:
          repository: CyberismoCom/module-base
          path: .tmp/module-base
          ref: main

      - name: Checkout cyberismo-docs repository for testing purposes
        uses: actions/checkout@v4
        with:
          repository: CyberismoCom/cyberismo-docs
          path: .tmp/cyberismo-docs
          ref: main
      - run: pnpm install --ignore-scripts
      - name: Check that cyberismo is not already installed
        run: |
          if command -v cyberismo &> /dev/null; then
            echo "cyberismo is already installed"
            exit 1
          fi

      - name: Setup cyberismo script
        run: |
          chmod +x scripts/cyberismo
          echo "$(pwd)/scripts" >> $GITHUB_PATH

      - name: Run CLI tests
        run: |
          cd tools/cli
          pnpm test


